"use client";

import { useEffect, useRef, useState, ReactNode } from "react";
import { BookOpen, Users, ClipboardList, Settings, Plus, ArrowUpRight, Feather, Search, ChevronLeft, ChevronRight, Check, X, Undo2, Download, Share2, Printer, MessageCircle, Pencil, CircleHelp, ShieldCheck, ArrowLeft, CheckCircle2, Copy, FileText, RotateCcw, ZoomIn, ZoomOut } from "lucide-react";
import { useRegister } from "../lib/use-register";
import { categories, emptyRecords, Lesson, Mark, Records, Student, uid, today, recordSchema, lessonMessage } from "../lib/mentor";
import { download, pageImage, printLesson } from "../lib/exports";

type View="students"|"lesson"|"history"|"settings";
type Meta={surahs:[number,string,string,string,number,number,number][];pages:[number,number,number,number,number,number,number][]};
const nav=[{id:"students",label:"Students",icon:Users},{id:"lesson",label:"Take lesson",icon:BookOpen},{id:"history",label:"Lesson history",icon:ClipboardList},{id:"settings",label:"Settings",icon:Settings}] as const;
const initials=(s:string)=>s.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
function newLesson(s:Student,from=562,to=562,type:Lesson["type"]="Sabqi"):Lesson{return {id:uid(),studentId:s.id,studentName:s.name,date:today(),type,from,to,status:"draft",outcome:"Passed with revision",notes:"",assignment:"",marks:[]};}
function sampleRecords():Records {const s:Student={id:"sample-ahmed",name:"Ahmed Rahman",contact:"",group:"Morning hifz",notes:"Example student — practice freely.",created:today()};const l=newLesson(s);l.id="sample-lesson";l.marks=[{id:"sample-mark",page:562,x:.38,y:.401,category:"prompt",reference:"Al-Mulk 4",note:"Repeat the phrase without prompting.",selfCorrected:false,resolved:false}];return {teacher:"",students:[s,{...s,id:"sample-yusuf",name:"Yusuf Abdullah"},{...s,id:"sample-maryam",name:"Maryam Hasan",group:"Afternoon hifz"}],lessons:[l]};}
function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const d=ref.current;return()=>d?.close()},[]);return <dialog ref={ref} className={wide?"modal wide":"modal"} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal-head"><h2>{title}</h2><button className="icon" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</dialog>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}

export default function Home(){
 const register=useRegister();const [demo,setDemo]=useState<Records|null>(null);const records=demo??register.records;
 const [view,setView]=useState<View>("students"),[meta,setMeta]=useState<Meta|null>(null),[metaError,setMetaError]=useState(false),[query,setQuery]=useState(""),[studentFilter,setStudentFilter]=useState("all"),[activeId,setActiveId]=useState<string|null>(null),[page,setPage]=useState(562),[zoom,setZoom]=useState(1),[category,setCategory]=useState<Mark["category"]>("prompt"),[notice,setNotice]=useState("");
 const [studentForm,setStudentForm]=useState<Student|null|"new">(null),[startFor,setStartFor]=useState<string|null>(null),[markId,setMarkId]=useState<string|null>(null),[finish,setFinish]=useState(false),[shareId,setShareId]=useState<string|null>(null),[help,setHelp]=useState(false),[imageError,setImageError]=useState(false),[imageLoaded,setImageLoaded]=useState(false),[exporting,setExporting]=useState(false);
 const current=records.lessons.find(l=>l.id===activeId),selectedMark=current?.marks.find(m=>m.id===markId),shared=records.lessons.find(l=>l.id===shareId);const writable=!!demo||(register.ready&&!register.locked);
 const fileInput=useRef<HTMLInputElement>(null);
 const completed=records.lessons.filter(l=>l.status==="complete");const unresolved=completed.flatMap(l=>l.marks).filter(m=>!m.resolved&&!m.selfCorrected).length;
 function change(next:Records){if(demo)setDemo(next);else register.change(next)}
 function updateLesson(next:Lesson){change({...records,lessons:records.lessons.map(l=>l.id===next.id?next:l)})}
 function openLesson(l:Lesson){setActiveId(l.id);setPage(l.from);setZoom(1);setView("lesson");setImageLoaded(false);setImageError(false)}
 function goto(p:number){if(!current||p===page)return;setPage(Math.max(current.from,Math.min(current.to,p)));setImageError(false);setImageLoaded(false)}
 function addMark(x=.5,y=.5,referenceOnly=false){if(!current||current.status!=="draft"||!writable)return;const m:Mark={id:uid(),page,x:Math.max(.015,Math.min(.985,x)),y:Math.max(.015,Math.min(.985,y)),category,location:referenceOnly?"reference":"point",reference:"",note:"",selfCorrected:false,resolved:false};updateLesson({...current,marks:[...current.marks,m]});return m.id;}
 function toast(t:string){setNotice(t)}
 function backup(){download(JSON.stringify({format:"hifz-mentor-backup-v1",exportedAt:new Date().toISOString(),records},null,2),`hifz-mentor-${today()}.json`);toast("Backup downloaded. Keep it in a safe place.")}
 useEffect(()=>{fetch("/quran/metadata.json").then(r=>{if(!r.ok)throw Error();return r.json() as Promise<Meta>}).then(setMeta).catch(()=>setMetaError(true))},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(""),6000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(view!=="lesson"||!current||document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA/.test((e.target as HTMLElement).tagName))return;if(e.key==="ArrowRight"){e.preventDefault();goto(page+1)}if(e.key==="ArrowLeft"){e.preventDefault();goto(page-1)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[page,current,view]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,opts:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{context.registerTool({name:"list_mentor_students",description:"List the students visible in the current Hifz Mentor register.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw Error("Expected an empty object");return records.students.map(s=>({id:s.id,name:s.name,group:s.group}));}},{signal:lifecycle.signal})}catch{}return()=>lifecycle.abort()},[records.students]);
 const pageMeta=meta?.pages.find(p=>p[0]===page);const pageLabel=(p:number)=>{const pg=meta?.pages.find(x=>x[0]===p);if(!pg)return `Page ${p}`;const a=meta?.surahs.find(s=>s[0]===pg[1])?.[2];const b=meta?.surahs.find(s=>s[0]===pg[3])?.[2];return `${a} ${pg[2]}–${pg[1]===pg[3]?"":b+" "}${pg[4]}`};
 const ayahs=(p:number)=>{const pg=meta?.pages.find(x=>x[0]===p);if(!pg||!meta)return [];const result:string[]=[];for(let s=pg[1];s<=pg[3];s++){const sr=meta.surahs.find(x=>x[0]===s)!;for(let a=s===pg[1]?pg[2]:1;a<=(s===pg[3]?pg[4]:sr[4]);a++)result.push(`${sr[2]} ${a}`);}return result};

 return <div className="shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setView("students")}}><BookOpen/><span>Hifz Mentor<small>THE USTAD’S WORKSPACE</small></span></a><div className="nav-label">TEACH & GUIDE</div><nav>{nav.map(n=><button title={n.label} key={n.id} className={view===n.id?"active":""} onClick={()=>setView(n.id)}><n.icon/><span>{n.label}</span>{n.id==="students"&&records.students.length>0&&<b>{records.students.length}</b>}</button>)}</nav><div className="sidebar-note"><Feather/><p>Every correction is a step<br/>toward confident recitation.</p><button onClick={()=>setHelp(true)}><CircleHelp size={17}/>A little guidance</button></div><div className="teacher"><div className="avatar small">{records.teacher?initials(records.teacher):"HM"}</div><div><strong>{records.teacher||"Your teaching desk"}</strong><small>Ustad workspace</small></div></div></aside>
 <main><header><div className="breadcrumb">Workspace <span>/</span> <strong>{nav.find(n=>n.id===view)?.label}</strong></div><div className="header-right"><span className="saved"><ShieldCheck size={15}/>{demo?"Practice · not saved":register.status}</span><button className="icon" onClick={()=>setHelp(true)} aria-label="How to use Hifz Mentor"><CircleHelp size={19}/></button></div></header>
 {demo&&<div className="demo-banner"><span><strong>Practice workspace.</strong> These are example students; changes here are not saved.</span><button onClick={()=>{setDemo(null);setActiveId(null);setView("students")}}>Return to my register <X size={15}/></button></div>}
 {!demo&&register.error&&<div className="error-banner" role="alert"><span>{register.error}</span><div>{register.unauthorized?<a className="button primary" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in</a>:<button onClick={()=>register.retry()}>Retry</button>}{register.ready&&<button onClick={backup}>Download backup</button>}</div></div>}
 {!demo&&register.recovery&&<div className="error-banner"><span>Earlier unsaved changes were found. Your saved register has also changed. Download the earlier changes before continuing.</span><button onClick={()=>download(JSON.stringify({format:"hifz-mentor-backup-v1",records:register.recovery},null,2),"recovered-hifz-mentor.json")}>Download recovered changes</button><button onClick={register.dismissRecovery}>Keep saved register</button></div>}<section className={`content ${view==="lesson"&&current?"lesson-content":""}`}>
 {view==="students"&&<><div className="eyebrow">BISMILLAH · LET’S BEGIN</div><div className="page-title"><div><h1>Your students</h1><p>A little guidance. Lasting progress.</p></div><button className="primary" disabled={!writable} onClick={()=>setStudentForm("new")}><Plus size={18}/>Add student</button></div>
 <div className="stats"><div><span>Students in your care</span><strong>{records.students.length.toString().padStart(2,"0")}</strong><Users/></div><div><span>Lessons completed</span><strong>{completed.length.toString().padStart(2,"0")}</strong><BookOpen/></div><div><span>Corrections to revisit</span><strong>{unresolved.toString().padStart(2,"0")}</strong><RotateCcw/></div></div>
 {records.students.length>0?<><div className="section-top"><h2>Student register <span>{records.students.length}</span></h2><label className="search"><Search size={18}/><input placeholder="Find a student…" aria-label="Find a student" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="student-list"><div className="table-head"><span>STUDENT</span><span>LAST LESSON</span><span>TO REVISIT</span><span></span></div>{records.students.filter(s=>`${s.name} ${s.group}`.toLowerCase().includes(query.toLowerCase())).map((s,i)=>{const lessons=records.lessons.filter(l=>l.studentId===s.id);const last=lessons.filter(l=>l.status==="complete").at(-1);const draft=lessons.find(l=>l.status==="draft");const marks=lessons.filter(l=>l.status==="complete").flatMap(l=>l.marks).filter(m=>!m.resolved&&!m.selfCorrected).length;return <div className="student-row" key={s.id}><button className="student-identity" onClick={()=>setStudentForm(s)}><span className={`avatar tone-${i%3}`}>{initials(s.name)}</span><span><strong>{s.name}</strong><small>{s.group||"Individual student"}</small></span></button><div className="last-lesson">{last?<><strong>{last.type} · pp. {last.from}–{last.to}</strong><small>{last.date}</small></>:<span className="muted">Ready for a first lesson</span>}</div><button className="correction-count" onClick={()=>{setStudentFilter(s.id);setView("history")}}>{marks?<><span className="amber-number">{marks}</span> corrections</>:<span className="muted">—</span>}</button><button className="lesson-button" onClick={()=>draft?openLesson(draft):setStartFor(s.id)}>{draft?"Resume lesson":"Take lesson"}<ArrowUpRight size={17}/></button></div>})}{!records.students.some(s=>`${s.name} ${s.group}`.toLowerCase().includes(query.toLowerCase()))&&<div className="empty-inline">No students match “{query}”.</div>}</div><div className="register-foot"><ShieldCheck size={15}/>Your register is private. Share only the lesson record you choose.</div></>:<div className="welcome"><span className="welcome-icon"><BookOpen size={36}/></span><h2>A new chapter starts here.</h2><p>Add your first student to take a lesson, mark mistakes,<br className="desktop"/> and send a personal correction record.</p><div className="actions center"><button className="primary" disabled={!writable} onClick={()=>setStudentForm("new")}><Plus size={18}/>Add your first student</button><button onClick={()=>{const d=sampleRecords();setDemo(d);openLesson(d.lessons[0])}}>Try a sample lesson <ArrowUpRight size={18}/></button></div></div>}
 <div className="quiet-tip"><span>01</span><div><strong>Begin each lesson with the last correction.</strong><p>A quick recheck helps turn a difficult passage into confident recall.</p></div></div></>}

 {view==="lesson"&&!current&&<><div className="eyebrow">LISTEN · MARK · GUIDE</div><div className="page-title"><div><h1>Take a lesson</h1><p>Choose a student and give the recitation your full attention.</p></div></div><div className="welcome"><BookOpen size={36}/><h2>Whose lesson is next?</h2>{records.students.length?<><div className="student-picker">{records.students.map(s=><button key={s.id} onClick={()=>{const d=records.lessons.find(l=>l.studentId===s.id&&l.status==="draft");d?openLesson(d):setStartFor(s.id)}}><span className="avatar small">{initials(s.name)}</span>{s.name}<ArrowUpRight size={18}/></button>)}</div></>:<><p>Your student register is ready for its first name.</p><button className="primary" disabled={!writable} onClick={()=>setStudentForm("new")}>Add student</button></>}</div></>}
 {view==="lesson"&&current&&<><div className="lesson-heading"><div><button className="text-button back" onClick={()=>{setActiveId(null);setView("students")}}><ArrowLeft size={15}/>Back to students</button><div className="title-line"><h1>{current.studentName}</h1><span className="pill">{current.type}</span><span className={`pill ${current.status==="complete"?"success":"neutral"}`}>{current.status==="draft"?"Lesson in progress":"Completed lesson"}</span></div><p>{current.date} <span className="dot-separator">·</span> Pages {current.from}–{current.to} <span className="dot-separator">·</span> {current.marks.length} {current.marks.length===1?"correction":"corrections"}</p></div><button className="primary" disabled={!writable} onClick={()=>current.status==="draft"?setFinish(true):setShareId(current.id)}>{current.status==="draft"?<Check size={18}/>:<Share2 size={18}/>} {current.status==="draft"?"Finish lesson":"Share record"}</button></div>
 <div className="lesson-grid"><div className="reader"><div className="reader-toolbar"><div className="page-navigation"><button className="icon" aria-label="Previous page" disabled={page<=current.from} onClick={()=>goto(page-1)}><ChevronLeft size={18}/></button><label>Page <select aria-label="Mushaf page" value={page} onChange={e=>goto(+e.target.value)}>{Array.from({length:current.to-current.from+1},(_,i)=>current.from+i).map(p=><option key={p}>{p}</option>)}</select></label><button className="icon" aria-label="Next page" disabled={page>=current.to} onClick={()=>goto(page+1)}><ChevronRight size={18}/></button></div><span className="reader-surah">{pageLabel(page)} {pageMeta&&<small>Juz {pageMeta[5]}</small>}</span><div className="zoom"><button className="icon" aria-label="Zoom out" disabled={zoom<=1} onClick={()=>setZoom(z=>Math.max(1,z-.25))}><ZoomOut size={18}/></button><button className="icon" aria-label="Zoom in" disabled={zoom>=2} onClick={()=>setZoom(z=>Math.min(2,z+.25))}><ZoomIn size={18}/></button></div></div><div className="reader-hint"><Pencil size={14}/>{current.status==="draft"?"Choose a mistake type, then tap its place on the page.":"Select a numbered mark to review the correction."}</div><div className="mushaf-scroll"><div className="mushaf-page" style={{width:`${zoom*100}%`}} onClick={e=>{if(!imageLoaded||imageError)return;const box=e.currentTarget.getBoundingClientRect();addMark((e.clientX-box.left)/box.width,(e.clientY-box.top)/box.height)}}><img key={page} src={`/quran/${String(page).padStart(3,"0")}.webp`} alt={`Madinah Mushaf page ${page}, ${pageLabel(page)}`} draggable={false} onLoad={()=>setImageLoaded(true)} onError={()=>setImageError(true)}/>{!imageError&&current.marks.map((m,i)=>m.page===page&&m.location!=="reference"?<button key={m.id} className={`page-mark ${m.resolved?"resolved":""}`} style={{left:`${m.x*100}%`,top:`${m.y*100}%`,borderColor:categories.find(c=>c.id===m.category)!.color}} aria-label={`Correction ${i+1}: ${categories.find(c=>c.id===m.category)!.label}`} onClick={e=>{e.stopPropagation();setMarkId(m.id)}}><span style={{background:categories.find(c=>c.id===m.category)!.color}}>{m.resolved?"✓":i+1}</span></button>:null)}</div>{imageError&&<div className="notice">This Mushaf page could not load. Reconnect and try another page, or use “Add by reference” to keep taking the lesson.</div>}</div><div className="reader-footer"><span>Madinah Mushaf · Hafs · 604 pages</span><span>← → to turn pages</span></div></div>
 <aside className="lesson-panel">{current.status==="draft"&&<div className="panel"><div className="panel-title"><h3>Mark a correction</h3><span className="step">01</span></div><div className="category-grid">{categories.map(c=><button key={c.id} className={category===c.id?"selected":""} style={{"--mark-color":c.color} as React.CSSProperties} onClick={()=>setCategory(c.id)}><span className="category-symbol">{c.short}</span>{c.label}</button>)}</div><div className="actions compact"><button disabled={!writable} onClick={()=>{const id=addMark(.5,.5,true);if(id)setMarkId(id)}}><Plus size={15}/>Add by reference</button><button aria-label="Undo last correction" title="Undo last correction" disabled={!current.marks.length||!writable} onClick={()=>updateLesson({...current,marks:current.marks.slice(0,-1)})}><Undo2 size={16}/></button></div></div>}
 <div className="panel"><div className="panel-title"><h3>Lesson corrections</h3><span className="count">{current.marks.length}</span></div>{current.marks.length?<div className="mark-list">{current.marks.map((m,i)=>{const c=categories.find(c=>c.id===m.category)!;return <button className="mark-row" key={m.id} onClick={()=>{goto(m.page);setMarkId(m.id)}}><span className="mark-number" style={{background:c.color+"18",color:c.color}}>{i+1}</span><span><strong>{c.label}</strong><small>p. {m.page}{m.reference?` · ${m.reference}`:(m.location==="reference"?" · Reference note":" · Page position")}</small>{(m.resolved||m.selfCorrected)&&<small className="green">{m.resolved?"Correct on recheck":"Self-corrected"}</small>}</span><ChevronRight size={15}/></button>})}</div>:<div className="no-marks"><Pencil size={24}/><p>No corrections yet.</p><small>Your marks will appear here as you listen.</small></div>}</div>
 {current.status==="draft"?<div className="panel"><h3>Lesson notes</h3><textarea aria-label="Lesson notes" maxLength={4000} placeholder="Encouragement, fluency, or a reminder…" rows={3} value={current.notes} onChange={e=>updateLesson({...current,notes:e.target.value})}/><p className="small-muted">Included in the student’s correction record.</p></div>:<div className="panel"><h3>{current.outcome}</h3><p>{current.notes||"No additional feedback."}</p>{current.assignment&&<><h4>Next assignment</h4><p>{current.assignment}</p></>}</div>}
 <div className="panel previous"><RotateCcw size={18}/><div><h3>From previous lessons</h3><p>{records.lessons.filter(l=>l.studentId===current.studentId&&l.id!==current.id&&l.status==="complete").flatMap(l=>l.marks).filter(m=>!m.resolved&&!m.selfCorrected).length} corrections to revisit</p><button className="text-button" onClick={()=>{setStudentFilter(current.studentId);setView("history")}}>Open student history <ArrowUpRight size={14}/></button></div></div></aside></div></>}

 {view==="history"&&<><div className="eyebrow">A RECORD OF PROGRESS</div><div className="page-title"><div><h1>Lesson history</h1><p>Keep the lesson. See the improvement.</p></div><select aria-label="Filter history by student" value={studentFilter} onChange={e=>setStudentFilter(e.target.value)}><option value="all">All students</option>{records.students.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div><div className="history-list">{[...records.lessons].reverse().filter(l=>studentFilter==="all"||l.studentId===studentFilter).map(l=><article className="history-card" key={l.id}><div className="history-date"><BookOpen size={22}/><span>{l.date}</span></div><div className="history-main"><div className="title-line"><h2>{l.studentName}</h2><span className="pill neutral">{l.type}</span></div><p>Pages {l.from}–{l.to} · {l.marks.length} corrections · {l.status==="draft"?"In progress":l.outcome}</p>{l.assignment&&<p className="assignment-preview"><strong>Next:</strong> {l.assignment}</p>}<div className="actions compact"><button onClick={()=>openLesson(l)}>{l.status==="draft"?"Resume lesson":"Review corrections"}<ArrowUpRight size={15}/></button>{l.status==="complete"&&<button onClick={()=>setShareId(l.id)}><Share2 size={15}/>Share record</button>}</div></div><span className={`pill ${l.status==="draft"?"neutral":"success"}`}>{l.status==="draft"?"Draft":"Completed"}</span></article>)}{!records.lessons.some(l=>studentFilter==="all"||l.studentId===studentFilter)&&<div className="welcome"><ClipboardList size={34}/><h2>Every lesson has a place.</h2><p>Completed lessons and saved drafts will appear here.</p><button className="primary" onClick={()=>{setActiveId(null);setView("lesson")}}>Take a lesson</button></div>}</div></>}

 {view==="settings"&&<><div className="eyebrow">YOUR WORKSPACE</div><div className="page-title"><div><h1>Settings & records</h1><p>A few details that make this teaching desk yours.</p></div></div><div className="settings-grid"><div className="panel"><h2>Teaching profile</h2><Field label="Ustad’s name"><input placeholder="Your name" maxLength={100} value={records.teacher} disabled={!writable} onChange={e=>change({...records,teacher:e.target.value})}/></Field><p className="small-muted">Appears on the correction records you share.</p></div><div className="panel"><h2>Your records, in your hands</h2><p>Download a backup of students, lessons, and every mark. Importing adds records with new IDs and keeps existing records unchanged.</p><div className="actions"><button disabled={!writable} onClick={backup}><Download size={17}/>Export backup</button><button disabled={!writable} onClick={()=>fileInput.current?.click()}>Import backup</button></div><input ref={fileInput} type="file" accept="application/json,.json" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>4_000_000)throw Error("Choose a Hifz Mentor backup smaller than 4 MB.");const j=JSON.parse(await f.text());if(j.format!=="hifz-mentor-backup-v1")throw Error("Choose a Hifz Mentor backup file.");const incoming=recordSchema.parse(j.records);const students=incoming.students.filter(s=>!records.students.some(x=>x.id===s.id));const lessons=incoming.lessons.filter(l=>!records.lessons.some(x=>x.id===l.id));const next=recordSchema.parse({...records,students:[...records.students,...students],lessons:[...records.lessons,...lessons]});change(next);toast(`Imported ${students.length} students and ${lessons.length} lessons. Existing records were kept.`)}catch{toast("Could not import this backup. Check its format and size; your register has not changed.")}e.target.value=""}}/></div><div className="panel"><ShieldCheck className="teal"/><h2>Private by default</h2><p>Student records are saved in your private workspace. A WhatsApp message, exported image, or PDF contains only the selected student’s lesson. Sending remains your choice.</p><h4>When the connection drops</h4><p>Keep the app open. Changes stay on screen until you retry saving. Download a backup before closing if saving is unavailable.</p></div><div className="panel"><h2>About Hifz Mentor</h2><p>Designed for the Ustad: listen, mark, and guide.</p><p className="small-muted">Madinah Mushaf (Hafs), 604 pages. Page images and Quran metadata supplied with Hifz Companion. The original Quran page files remain unchanged; corrections are stored separately.</p><button className="text-button" onClick={()=>setHelp(true)}>Read the quick guide <ArrowUpRight size={15}/></button></div></div></>}
 </section><footer>Hifz Mentor <span>With care, one lesson at a time.</span></footer></main>
 {notice&&<div className="toast" role="status">{notice}<button className="icon" onClick={()=>setNotice("")} aria-label="Dismiss message"><X size={16}/></button></div>}
 {metaError&&view==="lesson"&&<div className="toast" role="status">Quran references could not load. Page marking is still available.</div>}

 {studentForm&&<Modal title={studentForm==="new"?"Welcome a student":"Student details"} onClose={()=>setStudentForm(null)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const s:Student={id:studentForm==="new"?uid():studentForm.id,name:String(f.get("name")).trim(),contact:String(f.get("contact")),group:String(f.get("group")),notes:String(f.get("notes")),created:studentForm==="new"?today():studentForm.created};if(!s.name)return;change({...records,students:studentForm==="new"?[...records.students,s]:records.students.map(x=>x.id===s.id?s:x)});setStudentForm(null);toast("Student details updated.")}}><Field label="Student’s name"><input name="name" required autoFocus maxLength={100} defaultValue={studentForm==="new"?"":studentForm.name} placeholder="e.g. Ahmed Rahman"/></Field><Field label="Class or group"><input name="group" maxLength={300} defaultValue={studentForm==="new"?"":studentForm.group} placeholder="e.g. Morning hifz"/></Field><Field label="Student / guardian WhatsApp (optional)"><input name="contact" type="tel" maxLength={40} defaultValue={studentForm==="new"?"":studentForm.contact} placeholder="International format, e.g. +880…"/></Field><Field label="Private teaching notes"><textarea name="notes" maxLength={3000} rows={3} defaultValue={studentForm==="new"?"":studentForm.notes} placeholder="Background, learning goals, or reminders…"/></Field><p className="small-muted">Private notes are not included in shared lesson records.</p><div className="modal-actions"><button type="button" onClick={()=>setStudentForm(null)}>Cancel</button><button className="primary" disabled={!writable} type="submit">Save student <Check size={16}/></button></div></form></Modal>}
 {startFor&&<Modal title="Begin a lesson" onClose={()=>setStartFor(null)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),from=+String(f.get("from")),to=+String(f.get("to"));if(to<from){toast("The last page must be the same as or after the first page.");return;}const s=records.students.find(s=>s.id===startFor)!;const l=newLesson(s,from,to,f.get("type") as Lesson["type"]);change({...records,lessons:[...records.lessons,l]});openLesson(l);setStartFor(null)}}><div className="student-label"><span className="avatar">{initials(records.students.find(s=>s.id===startFor)?.name||"")}</span><strong>{records.students.find(s=>s.id===startFor)?.name}</strong></div><Field label="Lesson type"><select name="type" defaultValue="Sabqi"><option>Sabaq</option><option>Sabqi</option><option>Manzil</option></select></Field><Field label="Jump to a surah (sets page range)"><select defaultValue="" onChange={e=>{const f=e.target.form!;const p=meta?.surahs.find(s=>s[0]===+e.target.value)?.[6];if(p){(f.elements.namedItem("from") as HTMLInputElement).value=String(p);(f.elements.namedItem("to") as HTMLInputElement).value=String(p)}}}><option value="">Choose a surah…</option>{meta?.surahs.map(s=><option key={s[0]} value={s[0]}>{s[0]}. {s[2]} · {s[1]}</option>)}</select></Field><div className="form-grid"><Field label="First Mushaf page"><input name="from" type="number" min={1} max={604} required defaultValue={1}/></Field><Field label="Last Mushaf page"><input name="to" type="number" min={1} max={604} required defaultValue={1}/></Field></div><p className="small-muted">Use the printed Madinah Mushaf page numbers. You can note a partial-page ayah range in lesson notes.</p><div className="modal-actions"><button type="button" onClick={()=>setStartFor(null)}>Cancel</button><button type="submit" className="primary" disabled={!writable}>Start listening <ArrowUpRight size={17}/></button></div></form></Modal>}
 {selectedMark&&current&&<Modal title={`Correction ${current.marks.indexOf(selectedMark)+1}`} onClose={()=>setMarkId(null)}><div className="mark-detail"><p className="small-muted">Mushaf page {selectedMark.page} · {pageLabel(selectedMark.page)}</p><Field label="Mistake type"><select disabled={current.status!=="draft"} value={selectedMark.category} onChange={e=>updateLesson({...current,marks:current.marks.map(m=>m.id===selectedMark.id?{...m,category:e.target.value as Mark["category"]}:m)})}>{categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></Field><Field label="Ayah reference (optional)"><select disabled={current.status!=="draft"} value={selectedMark.reference} onChange={e=>updateLesson({...current,marks:current.marks.map(m=>m.id===selectedMark.id?{...m,reference:e.target.value}:m)})}><option value="">Page position only</option>{ayahs(selectedMark.page).map(a=><option key={a}>{a}</option>)}</select></Field><Field label="Correction / practice instruction"><textarea disabled={current.status!=="draft"} rows={3} maxLength={1000} value={selectedMark.note} onChange={e=>updateLesson({...current,marks:current.marks.map(m=>m.id===selectedMark.id?{...m,note:e.target.value}:m)})} placeholder="What should the student practise?"/></Field><label className="checkbox"><input type="checkbox" disabled={current.status!=="draft"} checked={selectedMark.selfCorrected} onChange={e=>updateLesson({...current,marks:current.marks.map(m=>m.id===selectedMark.id?{...m,selfCorrected:e.target.checked}:m)})}/>Student self-corrected</label>{current.status==="complete"&&<label className="checkbox"><input type="checkbox" checked={selectedMark.resolved} onChange={e=>updateLesson({...current,marks:current.marks.map(m=>m.id===selectedMark.id?{...m,resolved:e.target.checked}:m)})}/>Correct on recheck — keep the original record</label>}<div className="modal-actions">{current.status==="draft"&&<button className="danger" onClick={()=>{updateLesson({...current,marks:current.marks.filter(m=>m.id!==selectedMark.id)});setMarkId(null)}}>Remove mark</button>}<button className="primary" onClick={()=>setMarkId(null)}>Done <Check size={17}/></button></div></div></Modal>}
 {finish&&current&&<Modal title="A lesson worth keeping" onClose={()=>setFinish(false)}><p>{current.studentName} · {current.type} · {current.marks.length} corrections</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);updateLesson({...current,status:"complete",outcome:f.get("outcome") as Lesson["outcome"],notes:String(f.get("notes")),assignment:String(f.get("assignment"))});setFinish(false);setShareId(current.id)}}><Field label="Lesson outcome"><select name="outcome" defaultValue={current.marks.length?"Passed with revision":"Passed"}><option>Passed</option><option>Passed with revision</option><option>Repeat</option></select></Field><Field label="Feedback for the student"><textarea name="notes" maxLength={4000} rows={3} defaultValue={current.notes} placeholder="A word of encouragement and what to focus on…"/></Field><Field label="Next lesson / revision assignment"><textarea name="assignment" maxLength={2000} rows={3} defaultValue={current.assignment} placeholder="Passage to prepare, practice instructions, and due date…"/></Field><div className="modal-actions"><button type="button" onClick={()=>setFinish(false)}>Keep listening</button><button className="primary" type="submit">Complete & review <Check size={17}/></button></div></form></Modal>}
 {shared&&<Modal title="Share the lesson record" wide onClose={()=>setShareId(null)}><div className="share-heading"><CheckCircle2 size={28}/><div><strong>{shared.studentName}</strong><p>{shared.type} · {shared.date} · {shared.outcome}</p></div></div><pre className="message-preview">{lessonMessage(shared,records.teacher)}</pre><div className="share-options"><button className="primary" onClick={()=>{const c=records.students.find(s=>s.id===shared.studentId)?.contact.replace(/\D/g,"")||"";window.open(`https://wa.me/${c}?text=${encodeURIComponent(lessonMessage(shared,records.teacher))}`,"_blank","noopener,noreferrer")}}><MessageCircle size={18}/>Open WhatsApp</button><button onClick={async()=>{try{await navigator.clipboard.writeText(lessonMessage(shared,records.teacher));toast("Lesson message copied.")}catch{download(lessonMessage(shared,records.teacher),"lesson-record.txt","text/plain");toast("Message downloaded as text.")}}}><Copy size={17}/>Copy message</button><button onClick={()=>{try{printLesson(shared,records.teacher)}catch(e){toast((e as Error).message)}}}><Printer size={18}/>Print / Save PDF</button><button disabled={exporting} onClick={async()=>{setExporting(true);try{const p=shared.marks[0]?.page??shared.from;const b=await pageImage(shared,p);download(b,`${shared.studentName.replace(/[^a-zA-Z0-9]/g,"-")}-page-${p}.png`);toast(`Marked page ${p} downloaded. The PDF includes all marked pages.`)}catch{toast("The page image could not be created. Check your connection and retry.")}finally{setExporting(false)}}}><Download size={18}/>{exporting?"Preparing image…":"Download marked page"}</button><button onClick={async()=>{try{if(navigator.share)await navigator.share({title:"Hifz Mentor lesson record",text:lessonMessage(shared,records.teacher)});else{download(lessonMessage(shared,records.teacher),"lesson-record.txt","text/plain");toast("Message downloaded for sharing.")}}catch(e){if((e as Error).name!=="AbortError")toast("Sharing unavailable here. Use Copy message or download the record.")}}}><Share2 size={17}/>More sharing options</button></div><p className="small-muted">WhatsApp opens a message for you to review and send. Attach the downloaded PDF or image yourself. No message is sent automatically.</p><div className="modal-actions"><button onClick={()=>setShareId(null)}>Done</button></div></Modal>}
 {help&&<Modal title="A little guidance" onClose={()=>setHelp(false)}><ol className="guide"><li><strong>Add your students.</strong><p>Keep a class name and optional guardian contact in each profile.</p></li><li><strong>Listen and mark.</strong><p>Choose Sabaq, Sabqi, or Manzil and a page range. Select a mistake type, then tap the page. Open a numbered mark to add an ayah reference or instruction.</p></li><li><strong>Finish with direction.</strong><p>Record the outcome, encouragement, and next assignment.</p></li><li><strong>Share and revisit.</strong><p>Send a message, PDF, or marked image. At the next lesson, open the old correction and tick “Correct on recheck”.</p></li></ol><div className="notice">The Ustad makes every assessment. Hifz Mentor does not automatically judge recitation.</div><div className="modal-actions"><button className="primary" onClick={()=>setHelp(false)}>Ready to begin</button></div></Modal>}
 </div>;
}




