"use client";
import { useEffect, useRef, useState } from "react";
import { ChevronLeft, ChevronRight, ZoomIn, ZoomOut, Maximize2, Minimize2, Highlighter, Pencil } from "lucide-react";
import { categories, Lesson, Mark, uid } from "../lib/mentor";

type Verse={key:string;text:string};
type Meta={surahs:[number,string,string,string,number,number,number][];pages:[number,number,number,number,number,number,number][]};
export function LessonReader({lesson,page,goto,meta,writable,category,onAdd,onOpen}:{lesson:Lesson;page:number;goto:(p:number)=>void;meta:Meta|null;writable:boolean;category:Mark["category"];onAdd:(marks:Mark[])=>void;onOpen:(id:string)=>void}){
 const [mode,setMode]=useState<"text"|"mushaf">("text"),[zoom,setZoom]=useState(1),[fit,setFit]=useState(true),[focus,setFocus]=useState(false),[tool,setTool]=useState<"point"|"area">("area"),[verses,setVerses]=useState<Verse[]>([]),[error,setError]=useState(false),[retry,setRetry]=useState(0),[loaded,setLoaded]=useState(false),[imageError,setImageError]=useState(false),[selection,setSelection]=useState<{key:string;start:number;end:number}|null>(null),[drag,setDrag]=useState<{x:number;y:number;endX:number;endY:number}|null>(null);
 const textRef=useRef<HTMLDivElement>(null);const canEdit=writable&&lesson.status==="draft"&&lesson.marks.length<500;
 useEffect(()=>{const ac=new AbortController();setVerses([]);setError(false);setSelection(null);setLoaded(false);setImageError(false);setDrag(null);fetch(`/quran/text/${page}.json`,{signal:ac.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<Verse[]>}).then(setVerses).catch(e=>{if(e.name!=="AbortError")setError(true)});return()=>ac.abort()},[page,retry]);
 useEffect(()=>{if(!focus)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setFocus(false)};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[focus]);
 const pm=meta?.pages.find(p=>p[0]===page);const label=(key:string)=>{const [s,a]=key.split(":").map(Number);return `${meta?.surahs.find(x=>x[0]===s)?.[2]??`Surah ${s}`} ${a}`};
 const base=():Mark=>({id:uid(),page,x:0,y:0,category,reference:"",note:"",selfCorrected:false,resolved:false});
 function highlight(v:Verse,start:number,end:number){if(!canEdit)return;const words=v.text.split(/\s+/);const existing=lesson.marks.find(m=>m.location==="text"&&m.verseKey===v.key&&m.wordStart===start&&m.wordEnd===end);if(existing){onOpen(existing.id);return}onAdd([{...base(),location:"text",verseKey:v.key,wordStart:start,wordEnd:end,selectedText:words.slice(start,end+1).join(" "),reference:label(v.key)}]);setSelection(null);window.getSelection()?.removeAllRanges()}
 function captureSelection(){const s=window.getSelection();if(!s||s.isCollapsed||!s.rangeCount)return;const range=s.getRangeAt(0);const elements=Array.from(textRef.current?.querySelectorAll<HTMLElement>('[data-word]')??[]).filter(el=>range.intersectsNode(el));if(!elements.length)return;const first=elements[0],last=elements[elements.length-1];if(first.dataset.verse!==last.dataset.verse){setSelection(null);return}setSelection({key:first.dataset.verse!,start:Number(first.dataset.word),end:Number(last.dataset.word)})}
 function point(e:React.PointerEvent<HTMLDivElement>){const b=e.currentTarget.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),y:Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))}}
 const currentSelection=verses.find(v=>v.key===selection?.key);
 return <div className={`reader mentor-reader ${focus?"reader-focus":""}`}>
  <div className="reading-modes"><div role="group" aria-label="Reading view"><button className={mode==="text"?"active":""} aria-pressed={mode==="text"} onClick={()=>setMode("text")}>Text</button><button className={mode==="mushaf"?"active":""} aria-pressed={mode==="mushaf"} onClick={()=>setMode("mushaf")}>Mushaf</button></div><button className="text-button" onClick={()=>setFocus(!focus)}>{focus?<Minimize2 size={16}/>:<Maximize2 size={16}/>} {focus?"Exit focus":"Focus view"}</button></div>
  <div className="reader-toolbar"><div className="page-navigation"><button className="icon" aria-label="Previous page" disabled={page<=lesson.from} onClick={()=>goto(page-1)}><ChevronLeft size={18}/></button><label>Page <select value={page} onChange={e=>goto(+e.target.value)}>{Array.from({length:lesson.to-lesson.from+1},(_,i)=>lesson.from+i).map(p=><option key={p}>{p}</option>)}</select></label><button className="icon" aria-label="Next page" disabled={page>=lesson.to} onClick={()=>goto(page+1)}><ChevronRight size={18}/></button></div><span className="reader-surah">{pm?label(`${pm[1]}:${pm[2]}`):`Page ${page}`}<small>Juz {pm?.[5]??"—"}</small></span><div className="zoom"><button className="icon" aria-label="Reduce reading size" disabled={zoom<=.75} onClick={()=>setZoom(Math.max(.75,zoom-.25))}><ZoomOut size={18}/></button><button className="icon" aria-label="Increase reading size" disabled={zoom>=2} onClick={()=>setZoom(Math.min(2,zoom+.25))}><ZoomIn size={18}/></button></div></div>
  <div className="reader-tools">{mode==="mushaf"?<><button aria-pressed={fit} onClick={()=>{setFit(!fit);setZoom(1)}}>{fit?"Fit width":"Fit whole page"}</button>{lesson.status==="draft"&&<><button aria-pressed={tool==="area"} onClick={()=>setTool("area")}><Highlighter size={16}/>Yellow highlight</button><button aria-pressed={tool==="point"} onClick={()=>setTool("point")}><Pencil size={16}/>Point mark</button></>}</>:<span><Highlighter size={16}/>Tap a word, select a phrase, or mark a whole ayah.</span>}</div>
  {mode==="text"?<><div className="text-selection-bar">{selection&&currentSelection?<><span>Selected phrase · {label(selection.key)}</span><button className="yellow-action" disabled={!canEdit} onClick={()=>highlight(currentSelection,selection.start,selection.end)}>Highlight selected text</button><button onClick={()=>{setSelection(null);window.getSelection()?.removeAllRanges()}}>Cancel</button></>:<span>{lesson.status==="draft"?"Yellow highlights are saved with the selected mistake type. Select within one ayah at a time.":"Saved highlights · open a correction to review or recheck."}</span>}</div><div ref={textRef} className="quran-text-scroll" onPointerUp={captureSelection} onKeyUp={captureSelection} style={{"--quran-size":`${32*zoom}px`} as React.CSSProperties}>
   {error?<div className="notice">Arabic text could not load. <button onClick={()=>setRetry(retry+1)}>Retry</button></div>:!verses.length?<p role="status">Loading Quran text…</p>:verses.map(v=>{const words=v.text.split(/\s+/),marks=lesson.marks.filter(m=>m.location==="text"&&m.verseKey===v.key);return <article className="ayah-card" key={v.key}><div className="ayah-heading"><strong>{label(v.key)} <small>{v.key}</small></strong><button disabled={!canEdit} onClick={()=>highlight(v,0,words.length-1)}><Highlighter size={15}/>Mark ayah</button></div><div className="ayah-text" dir="rtl" lang="ar">{words.map((word,i)=>{const marked=marks.filter(m=>i>=m.wordStart!&&i<=m.wordEnd!);return <span key={i}><span data-word={i} data-verse={v.key} role="button" tabIndex={0} aria-label={`${word}${marked.length?", highlighted":""}`} aria-pressed={!!marked.length} className={`quran-word ${marked.length?"highlighted":""}`} onClick={()=>{if(window.getSelection()?.toString().trim())return;if(marked.length)onOpen(marked[0].id);else highlight(v,i,i)}} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();if(marked.length)onOpen(marked[0].id);else highlight(v,i,i)}}}>{word}</span>{" "}</span>})}<span className="ayah-end"> ۝{v.key.split(":")[1]}</span></div>{marks.length>0&&<div className="ayah-corrections">{marks.map(m=><button key={m.id} onClick={()=>onOpen(m.id)}>#{lesson.marks.indexOf(m)+1} · {categories.find(c=>c.id===m.category)?.label}{m.resolved?" · Rechecked":""}</button>)}</div>}</article>})}
  </div></>:<><div className="reader-hint">{lesson.status!=="draft"?"Open a mark to review its correction.":tool==="area"?"Drag across a word or line to highlight it yellow. For multiple lines, highlight each line separately.":"Tap the mistake’s position to place a numbered mark."}</div><div className={`mushaf-scroll ${fit?"fit-page":""}`}><div className="mushaf-page" style={{width:fit?"auto":`${zoom*100}%`,height:fit?`${Math.round(65*zoom)}vh`:"auto",touchAction:canEdit&&tool==="area"?"none":"auto"}} onPointerDown={e=>{if(!canEdit||!loaded||imageError||(e.target as HTMLElement).closest("button"))return;if(tool==="area"){const p=point(e);e.currentTarget.setPointerCapture(e.pointerId);setDrag({...p,endX:p.x,endY:p.y})}}} onPointerMove={e=>{if(drag){const p=point(e);setDrag({...drag,endX:p.x,endY:p.y})}}} onPointerCancel={()=>setDrag(null)} onPointerUp={e=>{if(!canEdit||!loaded||imageError||(e.target as HTMLElement).closest("button"))return;const p=point(e);if(tool==="point")onAdd([{...base(),location:"point",...p}]);else if(drag){const x=Math.min(drag.x,p.x),y=Math.min(drag.y,p.y),width=Math.abs(p.x-drag.x),height=Math.abs(p.y-drag.y);setDrag(null);if(width>.005&&height>.003)onAdd([{...base(),location:"area",x,y,width,height}])}}}>
   <img style={fit?{maxHeight:(65*zoom)+"vh"}:undefined} key={page+"-"+retry} src={`/quran/${String(page).padStart(3,"0")}.webp`} alt={`Madinah Mushaf page ${page}`} draggable={false} onLoad={()=>setLoaded(true)} onError={()=>setImageError(true)}/>
   {loaded&&!imageError&&lesson.marks.map((m,i)=>m.page===page&&(m.location==="point"||!m.location||m.location==="area")?<button key={m.id} className={m.location==="area"?"area-highlight":"page-mark"} style={m.location==="area"?{left:`${m.x*100}%`,top:`${m.y*100}%`,width:`${m.width!*100}%`,height:`${m.height!*100}%`}:{left:`${m.x*100}%`,top:`${m.y*100}%`,borderColor:categories.find(c=>c.id===m.category)!.color}} aria-label={`Open correction ${i+1}`} onClick={e=>{e.stopPropagation();onOpen(m.id)}}><span>{i+1}</span></button>:null)}
   {drag&&<div className="area-highlight drawing" style={{left:`${Math.min(drag.x,drag.endX)*100}%`,top:`${Math.min(drag.y,drag.endY)*100}%`,width:`${Math.abs(drag.endX-drag.x)*100}%`,height:`${Math.abs(drag.endY-drag.y)*100}%`}}/>}
  </div>{imageError&&<div className="notice">Page image could not load. <button onClick={()=>setRetry(retry+1)}>Retry</button></div>}</div>{lesson.marks.some(m=>m.page===page&&m.location==="text")&&<button className="text-marks-link" onClick={()=>setMode("text")}>View this page’s saved ayah and word highlights in Text view</button>}</>}
  <div className="reader-footer"><span>Madinah · Hafs · Page {page}</span><span>{mode==="text"?"Uthmani text · Quran.com":"Printed page · Hifz Companion"}</span></div>
 </div>
}

