import { categories, Lesson, lessonMessage } from "./mentor";
export function download(data:Blob|string,name:string,type="application/json") {const a=document.createElement("a");const url=URL.createObjectURL(typeof data==="string"?new Blob([data],{type}):data);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function printLesson(l:Lesson,teacher:string){
 const w=window.open("","_blank");if(!w)throw Error("Allow the correction sheet to open, then try again.");
 const pages=[...new Set(l.marks.map(m=>m.page))].sort((a,b)=>a-b);
 w.document.write(`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${esc(l.studentName)} — Lesson record</title><style>body{font:15px/1.6 Arial,sans-serif;color:#183b40;max-width:900px;margin:32px auto;padding:20px}h1{font:32px Georgia}h2{font:22px Georgia}.top{border-bottom:3px solid #175f57;padding-bottom:18px}.meta{color:#567174}.message{white-space:pre-wrap;overflow-wrap:anywhere}.page{break-before:page}.mushaf{position:relative;width:100%;max-width:620px;margin:auto}.mushaf img{width:100%;display:block}.mark{position:absolute;transform:translate(-50%,-50%);width:28px;height:28px;border:3px solid;border-radius:50%;background:#fff3}.mark b{position:absolute;top:-15px;left:-12px;font:700 13px Arial;background:white;border:1px solid;border-radius:30px;padding:2px 5px}.legend{font-size:13px}button{padding:12px 20px;background:#175f57;color:white;border:0;border-radius:6px;cursor:pointer}.hint{margin:15px 0}.footer{font-size:12px;color:#687d83;margin-top:25px}@media print{body{margin:0;padding:0}.no-print{display:none}.mushaf{max-width:150mm}.page{break-inside:avoid}h2{margin:0 0 8px}@page{size:A4;margin:14mm}}</style></head><body><div class="no-print"><button onclick="window.print()">Print / Save as PDF</button><p class="hint">Choose “Save as PDF” in the print dialog. Check all page images have loaded before printing.</p></div><div class="top"><div>HIFZ MENTOR · PERSONAL CORRECTION RECORD</div><h1>${esc(l.studentName)}</h1><div class="meta">${esc(l.date)} · ${esc(l.type)} · Madinah Mushaf ${l.from}–${l.to}${teacher?` · Ustad ${esc(teacher)}`:""}</div></div><div class="message">${esc(lessonMessage(l,teacher))}</div>${pages.map(p=>`<section class="page"><h2>Page ${p} · ${esc(l.studentName)}</h2><div class="mushaf"><img src="${location.origin}/quran/${String(p).padStart(3,"0")}.webp" alt="Mushaf page ${p}">${l.marks.map((m,i)=>m.page===p&&m.location!=="reference"?`<span class="mark" style="left:${m.x*100}%;top:${m.y*100}%;color:${categories.find(c=>c.id===m.category)!.color}"><b>${i+1}</b></span>`:"").join("")}</div><div class="legend">${l.marks.map((m,i)=>m.page===p?`${i+1}. ${esc(categories.find(c=>c.id===m.category)!.label)}${m.reference?` · ${esc(m.reference)}`:""}`:"").filter(Boolean).join(" &nbsp; · &nbsp; ")}</div></section>`).join("")}<p class="footer">Prepared with Hifz Mentor. Mushaf page images supplied with Hifz Companion; teacher annotations are a separate overlay.</p></body></html>`);w.document.close();
}
export async function pageImage(l:Lesson,page:number){const img=new Image();img.src=`/quran/${String(page).padStart(3,'0')}.webp`;await img.decode();const canvas=document.createElement("canvas");canvas.width=img.naturalWidth;canvas.height=img.naturalHeight+180;const ctx=canvas.getContext("2d")!;ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,100);ctx.fillStyle="#183b40";ctx.font="bold 28px Arial";ctx.fillText(`HIFZ MENTOR · ${l.studentName}`,35,40,canvas.width-70);ctx.font="22px Arial";ctx.fillText(`${l.date} · ${l.type} · Page ${page} · ${l.outcome}`,35,76);l.marks.forEach((m,i)=>{if(m.page!==page||m.location==="reference")return;const c=categories.find(c=>c.id===m.category)!;const x=m.x*img.naturalWidth,y=m.y*img.naturalHeight+100;ctx.strokeStyle=c.color;ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(x,y,30,22,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle=c.color;ctx.fillRect(x-35,y-42,35,30);ctx.fillStyle="white";ctx.font="bold 22px Arial";ctx.fillText(String(i+1),x-29,y-19);});ctx.fillStyle="#183b40";ctx.font="20px Arial";ctx.fillText("Numbers correspond to the accompanying lesson record.",35,canvas.height-30);return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error("Image export failed")),"image/png"));}

