export type Language="en"|"bn";
export const bengali:Record<string,string>={"Language":"ভাষা",
"Save & copy text":"সংরক্ষণ ও টেক্সট কপি করুন",
"Paste the copied message into WhatsApp or any chat app.":"কপি করা বার্তাটি হোয়াটসঅ্যাপ বা যেকোনো চ্যাট অ্যাপে পেস্ট করুন।",
"Started":"শুরু",
"Lesson saved. Message copied.":"পাঠ সংরক্ষিত। বার্তা কপি হয়েছে।",
"Lesson saved. Use Copy message below.":"পাঠ সংরক্ষিত। নিচের বার্তা কপি করুন ব্যবহার করুন।",
"Word-by-word meanings":"শব্দে শব্দে অর্থ",
"Word-by-word meanings are loaded from the Quran.com API v4 (Quran Foundation): English word-by-word translation (QUL resource 92) and Bengali word-by-word translation (QUL resource 94). The Quranic Universal Library credits QuranWBW.com for its word-by-word translations. Glosses are shown only when their Arabic words match the displayed ayah.":"শব্দে শব্দে অর্থ Quran.com API v4 (কুরআন ফাউন্ডেশন) থেকে লোড করা হয়: ইংরেজি শব্দার্থ (QUL রিসোর্স ৯২) ও বাংলা শব্দার্থ (QUL রিসোর্স ৯৪)। কুরআনিক ইউনিভার্সাল লাইব্রেরি তাদের শব্দার্থের জন্য QuranWBW.com-কে কৃতজ্ঞতা জানায়। প্রদর্শিত আয়াতের আরবি শব্দের সাথে মিললে তবেই অর্থ দেখানো হয়।",
"Word meanings: Quran.com API (Quran Foundation) · QUL word-by-word resource":"শব্দার্থ: Quran.com API (কুরআন ফাউন্ডেশন) · QUL শব্দে শব্দে রিসোর্স",
"Text highlights":"টেক্সট হাইলাইট",
"Sources & credits":"উৎস ও কৃতজ্ঞতা",
"Mushaf images: King Fahd Quran Printing Complex, supplied through Hifz Companion. Page metadata: quran-meta (Tanzil-derived). Arabic text: Quran.com. Arabic font: Amiri Quran.":"মুসহাফের ছবি: কিং ফাহদ কুরআন মুদ্রণ কমপ্লেক্স, হিফজ কম্প্যানিয়নের মাধ্যমে প্রাপ্ত। পৃষ্ঠার তথ্য: quran-meta (তানযিলভিত্তিক)। আরবি পাঠ: Quran.com। আরবি ফন্ট: আমিরি কুরআন।",
"English: Saheeh International. Bengali: Sheikh Mujibur Rahman, Darussalam Publication. Translations supplied by Quran.com.":"ইংরেজি: সহীহ ইন্টারন্যাশনাল। বাংলা: শেখ মুজিবুর রহমান, দারুসসালাম প্রকাশনা। অনুবাদ সরবরাহকারী: Quran.com।",
"Translation source catalogue":"অনুবাদের উৎস তালিকা",
"Select surah":"সূরা নির্বাচন করুন",
"Word by word":"শব্দে শব্দে","Off":"বন্ধ","Word meanings: Quran.com / Quran Foundation":"শব্দার্থ: Quran.com / কুরআন ফাউন্ডেশন","Word meanings could not load.":"শব্দার্থ লোড করা যায়নি।","Loading word meanings…":"শব্দার্থ লোড হচ্ছে…",
"Translation":"অনুবাদ","Arabic only":"শুধু আরবি","Translation could not load.":"অনুবাদ লোড করা যায়নি।","Loading translation…":"অনুবাদ লোড হচ্ছে…","Source: Saheeh International · Quran.com resource 20":"উৎস: সহীহ ইন্টারন্যাশনাল · Quran.com রিসোর্স ২০","Source: Sheikh Mujibur Rahman · Darussalam Publication · Quran.com resource 163":"উৎস: শেখ মুজিবুর রহমান · দারুসসালাম প্রকাশনা · Quran.com রিসোর্স ১৬৩",
"Save & open WhatsApp":"সংরক্ষণ করে হোয়াটসঅ্যাপ খুলুন",
"Other export options":"রপ্তানির অন্যান্য উপায়",
"Hifz Mentor · Mistakes to review":"হিফজ মেন্টর · পুনরায় দেখার ভুলসমূহ",
"In Hifz Companion: Progress → Import Feedback → paste this entire message.":"হিফজ কম্প্যানিয়নে: অগ্রগতি → ফিডব্যাক আমদানি → পুরো বার্তাটি পেস্ট করুন।",
"Surah (optional)":"সূরা (ঐচ্ছিক)","Use the default lesson page":"ডিফল্ট পাঠের পৃষ্ঠা ব্যবহার করুন","Choose a surah to open its first Mushaf page. You can turn pages during the lesson.":"সূরা বাছলে তার প্রথম মুসহাফ পৃষ্ঠা খুলবে। পাঠের সময় পৃষ্ঠা পরিবর্তন করতে পারবেন।",
"HIFZ MENTOR · LESSON RECORD":"হিফজ মেন্টর · পাঠের রেকর্ড","Mushaf pages":"মুসহাফের পৃষ্ঠা","Outcome":"ফলাফল","self-corrected":"নিজেই সংশোধন করেছে","No mistakes marked.":"কোনো ভুল চিহ্নিত হয়নি।","Feedback":"মন্তব্য","Next lesson":"পরবর্তী পাঠ","Ustad":"উস্তাদ",
"Hifz Mentor":"হিফজ মেন্টর","HM":"HM","English":"English",
"Students":"শিক্ষার্থী","Take lesson":"পাঠ নিন","Lesson history":"পাঠের ইতিহাস","Settings":"সেটিংস","Workspace":"কর্মক্ষেত্র","THE USTAD’S WORKSPACE":"উস্তাদের কর্মক্ষেত্র","TEACH & GUIDE":"শিক্ষা ও দিকনির্দেশনা","Every correction is a step":"প্রতিটি সংশোধন একটি পদক্ষেপ","toward confident recitation.":"আত্মবিশ্বাসী তিলাওয়াতের পথে।","A little guidance":"সংক্ষিপ্ত নির্দেশিকা","Your teaching desk":"আপনার শিক্ষাদানের স্থান","Ustad workspace":"উস্তাদের কর্মক্ষেত্র","Interface language":"ইন্টারফেসের ভাষা",
"BISMILLAH · LET’S BEGIN":"বিসমিল্লাহ · শুরু করি","Your students":"আপনার শিক্ষার্থীরা","A little guidance. Lasting progress.":"একটু দিকনির্দেশনা। স্থায়ী অগ্রগতি।","Add student":"শিক্ষার্থী যোগ করুন","Students in your care":"আপনার শিক্ষার্থী","Lessons completed":"সম্পন্ন পাঠ","Corrections to revisit":"পুনরায় দেখার সংশোধন","Student register":"শিক্ষার্থী তালিকা","Find a student…":"শিক্ষার্থী খুঁজুন…","Find a student":"শিক্ষার্থী খুঁজুন","STUDENT":"শিক্ষার্থী","LAST LESSON":"সর্বশেষ পাঠ","TO REVISIT":"পুনরায় দেখুন","Individual student":"স্বতন্ত্র শিক্ষার্থী","Ready for a first lesson":"প্রথম পাঠের জন্য প্রস্তুত","Resume lesson":"পাঠ চালিয়ে যান","No students match “":"এই নামে শিক্ষার্থী নেই: “","Your register is private. Share only the lesson record you choose.":"আপনার তালিকা ব্যক্তিগত। শুধু নির্বাচিত পাঠের রেকর্ড শেয়ার করুন।","A new chapter starts here.":"এখানেই নতুন অধ্যায়ের শুরু।","Add your first student to take a lesson, mark mistakes,":"পাঠ নিতে ও ভুল চিহ্নিত করতে প্রথম শিক্ষার্থী যোগ করুন,","and send a personal correction record.":"এবং ব্যক্তিগত সংশোধনের রেকর্ড পাঠান।","Add your first student":"প্রথম শিক্ষার্থী যোগ করুন","Try a sample lesson":"নমুনা পাঠ চেষ্টা করুন","Begin each lesson with the last correction.":"আগের সংশোধন দিয়ে প্রতিটি পাঠ শুরু করুন।","A quick recheck helps turn a difficult passage into confident recall.":"সংক্ষিপ্ত পুনঃযাচাই কঠিন অংশ মনে রাখতে সাহায্য করে।",
"LISTEN · MARK · GUIDE":"শুনুন · চিহ্নিত করুন · নির্দেশনা দিন","Take a lesson":"পাঠ নিন","Choose a student and give the recitation your full attention.":"শিক্ষার্থী বেছে নিয়ে মনোযোগ দিয়ে তিলাওয়াত শুনুন।","Whose lesson is next?":"এবার কার পাঠ?","Your student register is ready for its first name.":"আপনার তালিকায় প্রথম শিক্ষার্থী যোগ করুন।","Back to students":"শিক্ষার্থী তালিকায় ফিরুন","Lesson in progress":"পাঠ চলছে","Completed lesson":"সম্পন্ন পাঠ","Pages":"পৃষ্ঠা","Page":"পৃষ্ঠা","correction":"সংশোধন","corrections":"সংশোধন","Finish lesson":"পাঠ শেষ করুন","Share record":"রেকর্ড শেয়ার করুন","Mark a correction":"সংশোধন চিহ্নিত করুন","Add by reference":"রেফারেন্স দিয়ে যোগ করুন","Undo last correction":"শেষ সংশোধন বাতিল করুন","Lesson corrections":"পাঠের সংশোধন","p.":"পৃষ্ঠা","· Reference note":"· রেফারেন্স নোট","· Page position":"· পৃষ্ঠার অবস্থান","Correct on recheck":"পুনঃযাচাইয়ে সঠিক","Self-corrected":"নিজেই সংশোধন করেছে","No corrections yet.":"এখনো কোনো সংশোধন নেই।","Your marks will appear here as you listen.":"শোনার সময় চিহ্নিত সংশোধন এখানে দেখা যাবে।","Lesson notes":"পাঠের নোট","Encouragement, fluency, or a reminder…":"উৎসাহ, সাবলীলতা বা মনে রাখার বিষয়…","Included in the student’s correction record.":"শিক্ষার্থীর সংশোধনের রেকর্ডে অন্তর্ভুক্ত হবে।","No additional feedback.":"অতিরিক্ত মন্তব্য নেই।","Next assignment":"পরবর্তী করণীয়","From previous lessons":"আগের পাঠ থেকে","corrections to revisit":"সংশোধন পুনরায় দেখুন","Open student history":"শিক্ষার্থীর ইতিহাস দেখুন",
"A RECORD OF PROGRESS":"অগ্রগতির রেকর্ড","Keep the lesson. See the improvement.":"পাঠের রেকর্ড রাখুন। অগ্রগতি দেখুন।","Filter history by student":"শিক্ষার্থী অনুযায়ী ইতিহাস দেখুন","All students":"সব শিক্ষার্থী","corrections ·":"সংশোধন ·","In progress":"চলমান","Next:":"পরবর্তী:","Review corrections":"সংশোধন দেখুন","Draft":"খসড়া","Completed":"সম্পন্ন","Every lesson has a place.":"প্রতিটি পাঠের রেকর্ড থাকুক।","Completed lessons and saved drafts will appear here.":"সম্পন্ন পাঠ ও সংরক্ষিত খসড়া এখানে দেখা যাবে।",
"YOUR WORKSPACE":"আপনার কর্মক্ষেত্র","Settings & records":"সেটিংস ও রেকর্ড","A few details that make this teaching desk yours.":"আপনার শিক্ষাদানের প্রয়োজন অনুযায়ী সাজান।","Teaching profile":"শিক্ষকের পরিচিতি","Ustad’s name":"উস্তাদের নাম","Your name":"আপনার নাম","Appears on the correction records you share.":"শেয়ার করা সংশোধনের রেকর্ডে দেখা যাবে।","Your records, in your hands":"আপনার রেকর্ড আপনার হাতে","Download a backup of students, lessons, and every mark. Importing adds records with new IDs and keeps existing records unchanged.":"শিক্ষার্থী, পাঠ ও সব চিহ্নের ব্যাকআপ ডাউনলোড করুন। আমদানিতে নতুন আইডির রেকর্ড যোগ হয়; আগের রেকর্ড অপরিবর্তিত থাকে।","Export backup":"ব্যাকআপ ডাউনলোড","Import backup":"ব্যাকআপ আমদানি","Private by default":"ডিফল্টভাবে ব্যক্তিগত","Student records are saved in your private workspace. A WhatsApp message, exported image, or PDF contains only the selected student’s lesson. Sending remains your choice.":"শিক্ষার্থীর রেকর্ড আপনার ব্যক্তিগত কর্মক্ষেত্রে সংরক্ষিত থাকে। WhatsApp বার্তা, ছবি বা PDF-এ শুধু নির্বাচিত শিক্ষার্থীর পাঠ থাকে। পাঠানোর সিদ্ধান্ত আপনার।","When the connection drops":"সংযোগ বিচ্ছিন্ন হলে","Keep the app open. Changes stay on screen until you retry saving. Download a backup before closing if saving is unavailable.":"অ্যাপ খোলা রাখুন এবং আবার সংরক্ষণের চেষ্টা করুন। সংরক্ষণ সম্ভব না হলে বন্ধ করার আগে ব্যাকআপ ডাউনলোড করুন।","About Hifz Mentor":"হিফজ মেন্টর সম্পর্কে","Designed for the Ustad: listen, mark, and guide.":"উস্তাদের জন্য: শুনুন, চিহ্নিত করুন ও নির্দেশনা দিন।","Madinah Mushaf (Hafs), 604 pages. Page images and Quran metadata supplied with Hifz Companion. The original Quran page files remain unchanged; corrections are stored separately.":"মদিনা মুসহাফ (হাফস), ৬০৪ পৃষ্ঠা। পৃষ্ঠার ছবি ও কুরআনের তথ্য হিফজ কম্প্যানিয়ন থেকে নেওয়া। মূল পৃষ্ঠাগুলো অপরিবর্তিত থাকে; সংশোধন আলাদাভাবে সংরক্ষিত হয়।","Read the quick guide":"সংক্ষিপ্ত নির্দেশিকা পড়ুন","With care, one lesson at a time.":"যত্নের সঙ্গে, একেকটি পাঠ।","Dismiss message":"বার্তা বন্ধ করুন","Quran references could not load. Page marking is still available.":"কুরআনের রেফারেন্স লোড হয়নি। পৃষ্ঠায় চিহ্ন দেওয়া যাবে।",
"Welcome a student":"শিক্ষার্থী যোগ করুন","Student details":"শিক্ষার্থীর তথ্য","Student’s name":"শিক্ষার্থীর নাম","e.g. Ahmed Rahman":"যেমন: আহমেদ রহমান","Class or group":"শ্রেণি বা দল","e.g. Morning hifz":"যেমন: সকালের হিফজ","Student / guardian WhatsApp (optional)":"শিক্ষার্থী / অভিভাবকের WhatsApp (ঐচ্ছিক)","International format, e.g. +880…":"আন্তর্জাতিক নম্বর, যেমন +৮৮০…","Private teaching notes":"ব্যক্তিগত শিক্ষাদান নোট","Background, learning goals, or reminders…":"পটভূমি, শেখার লক্ষ্য বা মনে রাখার বিষয়…","Private notes are not included in shared lesson records.":"শেয়ার করা পাঠের রেকর্ডে ব্যক্তিগত নোট থাকে না।","Cancel":"বাতিল","Save student":"শিক্ষার্থী সংরক্ষণ","New lesson / test":"নতুন পাঠ / পরীক্ষা","Saved in this browser": "এই ব্রাউজারে সংরক্ষিত",
"Browser records could not be opened. Check browser storage permissions. Existing data has not been replaced.": "ব্রাউজারের রেকর্ড খোলা যায়নি। ব্রাউজারের স্টোরেজ অনুমতি যাচাই করুন। আগের তথ্য বদলানো হয়নি।",
"Records changed in another tab. Export your backup, then reload this page.": "অন্য ট্যাবে রেকর্ড পরিবর্তিত হয়েছে। ব্যাকআপ ডাউনলোড করে এই পৃষ্ঠাটি আবার খুলুন।",
"Student records are saved only in this browser. Export a backup before switching devices or clearing browser data. A WhatsApp message, exported image, or PDF contains only the selected student’s lesson. Sending remains your choice.": "শিক্ষার্থীর তথ্য শুধু এই ব্রাউজারে থাকে। ডিভাইস বদলানো বা ব্রাউজারের তথ্য মুছে ফেলার আগে ব্যাকআপ ডাউনলোড করুন। হোয়াটসঅ্যাপ বার্তা, ছবি বা PDF-এ শুধু নির্বাচিত শিক্ষার্থীর পাঠ থাকে। পাঠানোর সিদ্ধান্ত আপনার।",
"New lesson": "নতুন পাঠ",
  "Start new lesson": "নতুন পাঠ শুরু করুন",
  "Date":"তারিখ","Lesson type":"পাঠের ধরন","Sabaq":"সবক","Sabqi":"সবকি","Manzil":"মানজিল","Test":"পরীক্ষা","From page":"শুরুর পৃষ্ঠা","To page":"শেষ পৃষ্ঠা","Choose pages by surah":"সূরা অনুযায়ী পৃষ্ঠা বাছুন","Surah":"সূরা","Choose a surah…":"সূরা বাছুন…","Start":"শুরু করুন","Mushaf page":"মুসহাফের পৃষ্ঠা","Mistake type":"ভুলের ধরন","Ayah reference (optional)":"আয়াতের রেফারেন্স (ঐচ্ছিক)","Page position only":"শুধু পৃষ্ঠার অবস্থান","Correction / practice instruction":"সংশোধন / অনুশীলনের নির্দেশনা","What should the student practise?":"শিক্ষার্থী কী অনুশীলন করবে?","Student self-corrected":"শিক্ষার্থী নিজেই সংশোধন করেছে","Correct on recheck — keep the original record":"পুনঃযাচাইয়ে সঠিক — মূল রেকর্ড রাখুন","Remove mark":"চিহ্ন মুছুন","Done":"শেষ","A lesson worth keeping":"পাঠের ফলাফল","Lesson outcome":"পাঠের ফলাফল","Passed":"উত্তীর্ণ","Passed with revision":"পুনরাবৃত্তিসহ উত্তীর্ণ","Repeat":"আবার পড়তে হবে","Feedback for the student":"শিক্ষার্থীর জন্য মন্তব্য","A word of encouragement and what to focus on…":"উৎসাহ এবং যে বিষয়ে মনোযোগ দিতে হবে…","Next lesson / revision assignment":"পরবর্তী পাঠ / পুনরাবৃত্তির কাজ","Passage to prepare, practice instructions, and due date…":"প্রস্তুতির অংশ, অনুশীলনের নির্দেশনা ও নির্ধারিত তারিখ…","Keep listening":"শোনা চালিয়ে যান","Complete & review":"সম্পন্ন করে দেখুন","Share the lesson record":"পাঠের রেকর্ড শেয়ার করুন","Open WhatsApp":"WhatsApp খুলুন","Copy message":"বার্তা কপি করুন","Print / Save PDF":"প্রিন্ট / PDF সংরক্ষণ","Preparing image…":"ছবি তৈরি হচ্ছে…","Download marked page":"চিহ্নিত পৃষ্ঠা ডাউনলোড","More sharing options":"শেয়ারের আরও উপায়","WhatsApp opens a message for you to review and send. Attach the downloaded PDF or image yourself. No message is sent automatically.":"WhatsApp-এ বার্তাটি দেখে নিজে পাঠান। ডাউনলোড করা PDF বা ছবি নিজে যুক্ত করুন। কোনো বার্তা স্বয়ংক্রিয়ভাবে পাঠানো হয় না।",
"Add your students.":"শিক্ষার্থী যোগ করুন।","Keep a class name and optional guardian contact in each profile.":"প্রতিটি পরিচিতিতে শ্রেণির নাম ও ঐচ্ছিক অভিভাবকের যোগাযোগ রাখুন।","Listen and mark.":"শুনুন ও চিহ্নিত করুন।","Select a student and date to begin. Choose Text to highlight words, selected phrases, or a whole ayah in yellow. Choose Mushaf to drag a yellow highlight across a line or place a point mark. Open any correction to add instructions.":"শুরু করতে শিক্ষার্থী ও তারিখ বাছুন। শব্দ, বাক্যাংশ বা পুরো আয়াত হলুদ করতে টেক্সট বাছুন। পৃষ্ঠায় হলুদ চিহ্ন বা বিন্দু দিতে মুসহাফ বাছুন। নির্দেশনা যোগ করতে সংশোধন খুলুন।","Finish with direction.":"পরবর্তী নির্দেশনা দিয়ে শেষ করুন।","Record the outcome, encouragement, and next assignment.":"ফলাফল, উৎসাহ ও পরবর্তী কাজ লিখুন।","Share and revisit.":"শেয়ার করুন ও পুনরায় দেখুন।","Send a message, PDF, or marked image. At the next lesson, open the old correction and tick “Correct on recheck”.":"বার্তা, PDF বা চিহ্নিত ছবি পাঠান। পরের পাঠে পুরোনো সংশোধন খুলে ‘পুনঃযাচাইয়ে সঠিক’ বাছুন।","The Ustad makes every assessment. Hifz Mentor does not automatically judge recitation.":"সব মূল্যায়ন উস্তাদ করেন। হিফজ মেন্টর স্বয়ংক্রিয়ভাবে তিলাওয়াত বিচার করে না।","Ready to begin":"শুরু করতে প্রস্তুত","Close dialog":"উইন্ডো বন্ধ করুন","How to use Hifz Mentor":"হিফজ মেন্টর ব্যবহারের নিয়ম",
"Practice · not saved":"অনুশীলন · সংরক্ষিত নয়","Practice workspace.":"অনুশীলনের স্থান।","These are example students; changes here are not saved.":"এগুলো নমুনা শিক্ষার্থী; এখানকার পরিবর্তন সংরক্ষিত হয় না।","Return to my register":"আমার তালিকায় ফিরুন","Sign in":"সাইন ইন","Retry":"আবার চেষ্টা করুন","Download backup":"ব্যাকআপ ডাউনলোড","Earlier unsaved changes were found. Your saved register has also changed. Download the earlier changes before continuing.":"আগের অসংরক্ষিত পরিবর্তন পাওয়া গেছে। সংরক্ষিত তালিকাও বদলেছে। এগোনোর আগে আগের পরিবর্তন ডাউনলোড করুন।","Download recovered changes":"উদ্ধার করা পরিবর্তন ডাউনলোড","Keep saved register":"সংরক্ষিত তালিকা রাখুন",
"Reading view":"পড়ার ধরন","Text":"টেক্সট","Mushaf":"মুসহাফ","Exit focus":"ফোকাস বন্ধ করুন","Focus view":"ফোকাস ভিউ","Previous page":"আগের পৃষ্ঠা","Next page":"পরের পৃষ্ঠা","Juz":"পারা","Reduce reading size":"লেখা ছোট করুন","Increase reading size":"লেখা বড় করুন","Fit width":"প্রস্থ অনুযায়ী দেখুন","Fit whole page":"পুরো পৃষ্ঠা দেখুন","Yellow highlight":"হলুদ চিহ্ন","Point mark":"বিন্দু চিহ্ন","Tap a word, select a phrase, or mark a whole ayah.":"শব্দে চাপুন, বাক্যাংশ বাছুন বা পুরো আয়াত চিহ্নিত করুন।","Selected phrase ·":"নির্বাচিত অংশ ·","Highlight selected text":"নির্বাচিত লেখা হলুদ করুন","Yellow highlights are saved with the selected mistake type. Select within one ayah at a time.":"নির্বাচিত ভুলের ধরনসহ হলুদ চিহ্ন সংরক্ষিত হয়। একবারে একটি আয়াতের ভেতরে অংশ বাছুন।","Saved highlights · open a correction to review or recheck.":"সংরক্ষিত চিহ্ন · দেখতে বা পুনঃযাচাই করতে সংশোধন খুলুন।","Arabic text could not load.":"আরবি লেখা লোড হয়নি।","Loading Quran text…":"কুরআনের লেখা লোড হচ্ছে…","Mark ayah":"আয়াত চিহ্নিত করুন","· Rechecked":"· পুনঃযাচাই হয়েছে","Open a mark to review its correction.":"সংশোধন দেখতে চিহ্ন খুলুন।","Drag across a word or line to highlight it yellow. For multiple lines, highlight each line separately.":"শব্দ বা লাইনের ওপর টেনে হলুদ করুন। একাধিক লাইনের জন্য প্রতিটি লাইন আলাদা করে চিহ্নিত করুন।","Tap the mistake’s position to place a numbered mark.":"সংখ্যাযুক্ত চিহ্ন দিতে ভুলের স্থানে চাপুন।","Page image could not load.":"পৃষ্ঠার ছবি লোড হয়নি।","View this page’s saved ayah and word highlights in Text view":"এই পৃষ্ঠার সংরক্ষিত আয়াত ও শব্দের চিহ্ন টেক্সট ভিউতে দেখুন","Madinah · Hafs · Page":"মদিনা · হাফস · পৃষ্ঠা","Uthmani text · Quran.com":"উসমানি লেখা · Quran.com","Printed page · Hifz Companion":"মুদ্রিত পৃষ্ঠা · হিফজ কম্প্যানিয়ন","· pp.":"· পৃষ্ঠা",
"Prompt needed":"মনে করিয়ে দিতে হয়েছে","Word error":"শব্দে ভুল","Pronunciation":"উচ্চারণ","Tajwid":"তাজবিদ","Stop / start":"থামা / শুরু","Similar passage":"সদৃশ অংশ",
"Loading register…":"তালিকা লোড হচ্ছে…","Recovered unsaved changes":"অসংরক্ষিত পরিবর্তন উদ্ধার হয়েছে","All changes saved":"সব পরিবর্তন সংরক্ষিত","Register unavailable":"তালিকা পাওয়া যাচ্ছে না","Saving…":"সংরক্ষণ হচ্ছে…","Unsaved changes":"অসংরক্ষিত পরিবর্তন","Changes not saved":"পরিবর্তন সংরক্ষিত হয়নি",
"Backup downloaded. Keep it in a safe place.":"ব্যাকআপ ডাউনলোড হয়েছে। নিরাপদে রাখুন।","Student details updated.":"শিক্ষার্থীর তথ্য হালনাগাদ হয়েছে।","The last page must be the same as or after the first page.":"শেষ পৃষ্ঠা শুরুর পৃষ্ঠার সমান বা পরের হতে হবে।","Could not import this backup. Check its format and size; your register has not changed.":"ব্যাকআপ আমদানি হয়নি। ফরম্যাট ও আকার দেখুন; আপনার তালিকা বদলায়নি।","Lesson message copied.":"পাঠের বার্তা কপি হয়েছে।","Message downloaded as text.":"বার্তা টেক্সট হিসেবে ডাউনলোড হয়েছে।","The page image could not be created. Check your connection and retry.":"পৃষ্ঠার ছবি তৈরি হয়নি। সংযোগ দেখে আবার চেষ্টা করুন।","Message downloaded for sharing.":"শেয়ারের জন্য বার্তা ডাউনলোড হয়েছে।","Sharing unavailable here. Use Copy message or download the record.":"এখানে শেয়ার করা যাচ্ছে না। বার্তা কপি করুন বা রেকর্ড ডাউনলোড করুন।",
"Sign in to open your private register.":"ব্যক্তিগত তালিকা খুলতে সাইন ইন করুন।","Your register could not be loaded. Please retry.":"তালিকা লোড হয়নি। আবার চেষ্টা করুন।","Sign in before saving.":"সংরক্ষণের আগে সাইন ইন করুন।","Invalid request origin":"অনুরোধের উৎস সঠিক নয়","This register is too large. Export a backup before continuing.":"তালিকাটি অনেক বড়। এগোনোর আগে ব্যাকআপ নিন।","The record contains invalid fields.":"রেকর্ডের কিছু তথ্য সঠিক নয়।","This register changed on another device. Download your current backup, then reload before editing further.":"অন্য ডিভাইসে তালিকা বদলেছে। বর্তমান ব্যাকআপ ডাউনলোড করে পুনরায় লোড করুন।","Could not save. Your changes are still on this screen; retry or download a backup.":"সংরক্ষণ হয়নি। পরিবর্তন স্ক্রিনে আছে; আবার চেষ্টা করুন বা ব্যাকআপ নিন।"
};
export function translate(text:string|undefined,lang:Language):string{
 if(!text)return "";if(lang==="en")return text;const key=text.trim();if(bengali[key])return text.replace(key,bengali[key]);
 const correction=key.match(/^Correction (\d+)$/);if(correction)return `সংশোধন ${correction[1]}`;
 const open=key.match(/^Open correction (\d+)$/);if(open)return `সংশোধন ${open[1]} খুলুন`;
 const imported=key.match(/^Imported (\d+) students and (\d+) lessons\. Existing records were kept\.$/);if(imported)return `${imported[1]} জন শিক্ষার্থী ও ${imported[2]}টি পাঠ আমদানি হয়েছে। আগের রেকর্ড রাখা হয়েছে।`;
 const image=key.match(/^Marked page (\d+) downloaded\. The PDF includes all marked pages\.$/);if(image)return `চিহ্নিত পৃষ্ঠা ${image[1]} ডাউনলোড হয়েছে। PDF-এ সব চিহ্নিত পৃষ্ঠা আছে।`;
 return text;
}


